```{r}
library(tidyverse)
library(nycflights13)

airlines
```
```{r}
airports
```
```{r}
planes
```
```{r}
weather
```
it’s good practice to verify that they do indeed uniquely identify each observation
```{r}
planes %>% 
  count(tailnum) %>% 
  filter(n > 1)
```
```{r}
weather %>% 
  count(year, month, day, hour, origin) %>% 
  filter(n > 1)
```
```{r}
flights %>% 
  count(year, month, day, flight) %>% 
  filter(n > 1)
```
```{r}
flights %>% 
  count(year, month, day, tailnum) %>% 
  filter(n > 1)
```
```{r}
flights2 <- flights %>% 
  select(year:day, hour, origin, dest, tailnum, carrier)
flights2
```
```{r}
flights2 %>%
  select(-origin, -dest) %>% 
  left_join(airlines, by = "carrier")
```
```{r}
flights2 %>%
  select(-origin, -dest) %>% 
  mutate(name = airlines$name[match(carrier, airlines$carrier)])
```
```{r}
x <- tribble(
  ~key, ~val_x,
     1, "x1",
     2, "x2",
     3, "x3"
)
y <- tribble(
  ~key, ~val_y,
     1, "y1",
     2, "y2",
     4, "y3"
)

x %>% 
  inner_join(y, by = "key")
```
```{r}
x %>% 
  inner_join(y, by = "key")
```
```{r}
x <- tribble(
  ~key, ~val_x,
     1, "x1",
     2, "x2",
     2, "x3",
     3, "x4"
)
y <- tribble(
  ~key, ~val_y,
     1, "y1",
     2, "y2",
     2, "y3",
     3, "y4"
)
left_join(x, y, by = "key")
```
```{r}
flights2 %>% 
  left_join(weather)
```

```{r}
flights2 %>% 
  left_join(planes, by = "tailnum")

flights2 %>% 
  left_join(airports, c("dest" = "faa"))

flights2 %>% 
  left_join(airports, c("origin" = "faa"))
```
```{r}
top_dest <- flights %>%
  count(dest, sort = TRUE) %>%
  head(10)
top_dest
```
```{r}
flights %>% 
  filter(dest %in% top_dest$dest)
```
```{r}
flights %>% 
  semi_join(top_dest)
```
```{r}
flights %>%
  anti_join(planes, by = "tailnum") %>%
  count(tailnum, sort = TRUE)
```
```{r}
airports %>% count(alt, lon) %>% filter(n > 1)
```

```{r}
df1 <- tribble(
  ~x, ~y,
   1,  1,
   2,  1
)
df2 <- tribble(
  ~x, ~y,
   1,  1,
   1,  2
)

intersect(df1, df2)
union(df1, df2)
setdiff(df1, df2)
setdiff(df2, df1)
```


